import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  docs: [

    'HOME',

    {
      type: 'category',
      label: 'ProgrammingTips',
      items: [
        'ProgrammingTips/finite-state machine/fsm',


      ],
    },
    {
      type: 'category',
      label: 'StepperFocCtrl',
      items: [
        'StepperCtrl/simulation',
      ],
    },

    {
      type: 'category',
      label: 'FocController',
      items: [
        'FocController/foc_controller',
      ],
    },
    {
      type: 'category',
      label: 'Quadruped-sim',
      items: [
        'quadruped-sim/eigen/eigen',
        'quadruped-sim/load_robot/load_robot',
        'quadruped-sim/foot_swing_trajectory/foot_swing_trajectory'

      ],
    },

    {
      type: 'category',
      label: 'Linux',
      items: [
        {
          type: 'category',
          label: 'Imx6ull',
          items: [
            'Linux/Imx6ull/imx6ull_uboot_kernel/Imx6ull_uboot_kernel',
          ],
        },
        'Linux/irq/irq'

      ],
    }

    
  ],
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
